FRRouting/topotests

README.md

We cannot usermod the frr user until after we
create the user with adduser.
Signed-off-by: Donald Sharp <sharpd@cumulusnetworks.com>

Update Readme to have correct ordering for frr user

---

GUIDELINES.md
conftest.py
example-test/test_template.py
lib/test/test_json.py
lib/topogen.py
lib/topotest.py

This Pull Request implements support for JSON handling in Topogen:
* Get JSON output from vtysh output:
```py
router = tgen.router_list[0]
output = router.vtysh_cmd('show ip ospf json', isjson=True)
```
`output` now holds a Python dictionary generated from the JSON output.
* JSON dictionaries comparison function `json_cmp()` with special `assert` support.
I have also sneaked some other smaller fixes in the Pull Request:
* Allow users to run template with this syntax: `cd example-test/; ./test_template.py`
* Don't show useless backtraces when running `--topology-only` on old tests
* Added some test writing tips obtained while developing the JSON support

Topogen JSON support

---

example-test/test_template.py
lib/topogen.py
lib/topolog.py
lib/topotest.py

Add logging framework to improve execution output.
Changes:
* Output log files to directory: /tmp/topotests/<test-name>/<log-file>
* Add timestamps to log messages (so we can correlate events)
* Add new log file generated by Topogen per-equipment:
`/tmp/topotests/<test-name>/<equipment>.log`
It contains all equipments interaction output.
* Other small code improvements

import Topolog

---

lib/topogen.py
lib/topotest.py

Add check for the mpls kernel modules to additional places:
- diagnose_env() to show warning if they are missing
- daemon_available() function if checking for ldpd

Add check for mpls module to more places

---

conftest.py
lib/topolog.py

Previously, all logs from topolog were sent to stderr. This change will send INFO and DEBUG
to stderr and only the remaining ones to stderr.

lib: Change topology to output INFO and DEBUG to stdout

---

eigrp-topo1/r1/eigrpd.conf
eigrp-topo1/r1/show_ip_eigrp.ref
eigrp-topo1/r1/show_ip_route.ref
eigrp-topo1/r2/show_ip_eigrp.ref
eigrp-topo1/r2/show_ip_route.ref
eigrp-topo1/r3/eigrpd.conf
eigrp-topo1/r3/show_ip_eigrp.ref
eigrp-topo1/r3/show_ip_route.ref
eigrp-topo1/test_eigrp_topo1.py
lib/topogen.py
lib/topotest.py
pytest.ini

This takes PR #27 and corrects the output.

Eigrp correction

---

all-protocol-startup/test_all_protocol_startup.py
bgp_multiview_topo1/test_bgp_multiview_topo1.py
eigrp-topo1/test_eigrp_topo1.py
ldp-topo1/test_ldp_topo1.py
lib/topotest.py
ospf6-topo1/test_ospf6_topo1.py
rip-topo1/test_rip_topo1.py
ripng-topo1/test_ripng_topo1.py

- Cleanup output
- Kill daemons with SIGTERM first, only use signal 7 if no exit after 2 sec

Fix and cleanups

---

bgp-ecmp-topo1/test_bgp_ecmp_topo1.py

bgp-ecmp-topo1: Workaround for version check

---

README.md
SNIPPETS.md
lib/topogen.py
lib/topotest.py

This PR brings some improvements to topotest based on users feedback.
1. Added more documentation
2. Explained a `sleep` during the router stop
3. Changed `json_cmp` errors to always include diffs from the data structures
4. Demoted some log messages to informational

Topotest miscellaneous improvements

---

lib/topogen.py
lib/topotest.py

stopRouter: report when a process is being killed
only sleep if actually killed a process
add option to not sleep or conduct -7 kill
topogen stop: add wait parameter (defaults to old/wait)
when stopping routers, first stop all without waiting
then do a second pass where will wait if needed
Signed-off-by: Lou Berger <lberger@labn.net>

lib: speed up router shutdown

---

lib/topotest.py

Improved some messages to display which router is doing what, added code to remove PID files after `SIGKILL` and added check for empty PID directory.

Minor topotest informational messages change

---

lib/lutil.py

Signed-off-by: Lou Berger <lberger@labn.net>

lib: lutil - make it easier to spot command output and null output

---

ldp-vpls-topo1/r1/show_ip_ospf_neighbor.ref
ldp-vpls-topo1/r1/show_ip_ospf_neighbor.ref-no-neigh
ldp-vpls-topo1/r2/show_ip_ospf_neighbor.ref
ldp-vpls-topo1/r2/show_ip_ospf_neighbor.ref-no-neigh
ldp-vpls-topo1/r3/show_ip_ospf_neighbor.ref
ldp-vpls-topo1/r3/show_ip_ospf_neighbor.ref-no-neigh
ldp-vpls-topo1/test_ldp_vpls_topo1.py

Accept new format in ospf neighbor json output in addition to
old version. New format was introduced with PR1659

ldp-vpls-topo1: new format for ospf neighbor json

---

ldp-topo1/r1/show_mpls_table.ref-no-impl-null
ldp-topo1/r2/show_mpls_table.ref
ldp-topo1/r2/show_mpls_table.ref-no-impl-null
ldp-topo1/r3/show_mpls_table.ref
ldp-topo1/r3/show_mpls_table.ref-no-impl-null
ldp-topo1/r4/show_mpls_table.ref
ldp-topo1/r4/show_mpls_table.ref-no-impl-null
ldp-topo1/test_ldp_topo1.py

ldp-topo1: Support implicit-null and old format on "show_mpls_table"

---

lib/lutil.py

Prior behavior of luCommand was to convert newlines to spaces in DUT
output before pattern matching. New method operating in parallel uses
re.DOTALL to mimic same behavior and allow preserving original DUT output.
The original output is needed for some scripts that parse line-by-line.
There is also some test code to compare match results using the
old way and new way and log a message if they are different. After
some short time we can develop confidence that using this new method
will not break any existing tests.
Signed-off-by: G. Paul Ziemba <paulz@labn.net>

lib: lutil matching without changing newlines

---

bgp_multiview_topo1/r1/show_ip_bgp_view_1-post4.1.ref
bgp_multiview_topo1/r1/show_ip_bgp_view_2-post4.1.ref
bgp_multiview_topo1/r1/show_ip_bgp_view_3-post4.1.ref

For this test, vrf id in headers is unset

bgp_multiview_topo1: more fixes for header changes of PR 2045

---

bgp_l3vpn_to_bgp_vrf/customize.py
bgp_l3vpn_to_bgp_vrf/r1/zebra.conf
bgp_l3vpn_to_bgp_vrf/r3/zebra.conf
bgp_l3vpn_to_bgp_vrf/r4/zebra.conf
bgp_l3vpn_to_bgp_vrf/scripts/check_linux_mpls.py
lib/lutil.py

bgp_l3vpn_to_bgp_vrf: remote static routes left over from old test version
@beneslami noticed these vestigial routes - thanks!
lib: lutil - fix test numbering, add test number to command logging

minor topotest cleanup

---

lib/topogen.py
lib/topotest.py

Use directory per node, report cores stacks  and memory on exit

---

lib/bgprib.py

lib: bgprib - get human readable version of json commands for log

minor change to help debug failures via run longs

---

lib/topogen.py
lib/topotest.py

lib: Add support for staticd

---

bgp_vrf_netns/test_bgp_vrf_netns_topo.py

Signed-off-by: Philippe Guibert <philippe.guibert@6wind.com>

bgp_vrf_netns: swap the order of netns destruction

---

bgp_l3vpn_to_bgp_vrf/customize.py

use workaround described in 
https://github.com/FRRouting/frr/blob/stable/5.0/doc/user/installation.rst#id43 
for kernel version=4.15

bgp_l3vpn_to_bgp_vrf: use l3mdev_accept workaround for known kernel bug

---

all-protocol-startup/r1/show_bgp_ipv4-post5.0.ref

See: https://github.com/FRRouting/frr/pull/2837
Signed-off-by: Quentin Young <qlyoung@cumulusnetworks.com>

update ref file for cidr mask display

---

lib/topotest.py
ospf-topo1-vrf/r1/zebraroute.txt
ospf-topo1-vrf/r1/zebraroutedown.txt
ospf-topo1-vrf/r2/zebraroute.txt
ospf-topo1-vrf/r2/zebraroutedown.txt
ospf-topo1-vrf/r3/zebraroute.txt
ospf-topo1-vrf/r3/zebraroutedown.txt

Signed-off-by: Christian Franke <nobody@nowhere.ws>

lib/ospf-topo1-vrf: don't compare headers of show ip route

---

README.md
lib/topotest.py

lib: Add support for Ubuntu 18.04 with installed FRR package
