FRRouting/topotests

- lib/topotest.py
When we have a kernel sub version > 10 the float conversion
of the kernel version causes 4.10 to be less than 4.5
Get the kernel version in groups on <major>.<minor> and do
comparison that way
Signed-off-by: Donald Sharp <sharpd@cumulusnetworks.com>
> lib: Fix kernel version parsing

- GUIDELINES.md
- lib/topogen.py
- lib/topotest.py
- pytest.ini
Add support for a configuration file.
Currently the code re-uses the pytest.ini to load its configuration and has the following options:
* `verbosity`: allows to change the default verbosity of tests, so we don't have to touch test files to enable debugs.
* `frrdir` and `quaggadir`: allows non-default FRR or Quagga installation paths
* `routertype`: allows running topotest using a non-default router type (we only have `quagga` now)
* `memleak_path`: active memory leak tests without using environment variables and apply it globally for all tests
The options and defaults are already listed in pytest.ini commented out.
> Topogen Configuration File

- example-test/test_template.py
- lib/test/test_json.py
- lib/test/test_version.py
- lib/topogen.py
- lib/topotest.py
This is a collection of improvements to the topology generator Topogen to make writing tests easier and quicker.
Changelog:
* Add support for generic hosts (TopoHost) and ExaBGP peers (TopoExaBGP)
* TopoGear (the super class which all other types derives) now implements start()/stop(), so sub-classes can use it to implement startup/teardown function for equipments that will be called on pytest start and at the end
* Added error propagation capabilities. Using global variables for this is no longer necessary.
* Added support for list compare inside JSON data structures. json_cmp() now do the following additional checks: check for list item count (expect item count, expect declared items to exist at least once, expect list type)
* Added 'check_router_running' abstraction to avoid boiler …
> topogen improvements

- bgp_multiview_topo1/peer1/exabgp.cfg
- bgp_multiview_topo1/peer2/exabgp.cfg
- bgp_multiview_topo1/peer3/exabgp.cfg
- bgp_multiview_topo1/peer4/exabgp.cfg
- bgp_multiview_topo1/peer5/exabgp.cfg
- bgp_multiview_topo1/peer6/exabgp.cfg
- bgp_multiview_topo1/peer7/exabgp.cfg
- bgp_multiview_topo1/peer8/exabgp.cfg
- conftest.py
- lib/topogen.py
- lib/topotest.py
I've implemented an environment diagnostics routine that runs on every pytest initialization. This routine detects common mistakes on the environment configuration that usually causes silent errors.
The main objective here is to make errors clearer to new topotest adopters, so when they get non-working tests they might look at execution log and get clues.
Currently diagnostics are detecting the following errors:
* Bad FRR instalations (will abort on critical errors)
* Bad Quagga installations
* Look for required packages: mininet, gdb, iproute
* check exabgp version
* check for /tmp
* check ldp/mpls dependencies
I'm also sneaking in two other commits in this PR:
1. fix bgp_multiview_topo1 exabgp configuration to run on more linux distros
2. simplify router kernel check code
> topotest diagnostics

- lib/topotest.py
- ospf-topo1/test_ospf_topo1.py
- Remove a check for spf timer runtime in ospf test
- Disable LDP tests if required kernel modules are missing
> Fixes to run topotest on ARM7 testbeds (and more reliable on other systems)

- ldp-topo1/r1/show_ipv4_route.ref
- ldp-topo1/r2/show_ipv4_route.ref
- ldp-topo1/r3/show_ipv4_route.ref
- ldp-topo1/r4/show_ipv4_route.ref
- ldp-topo1/test_ldp_topo1.py
Signed-off-by: Martin Winter <mwinter@netdef.org>
> ldp-topo1: Use 'label implicit-null' for implicit labels

- lib/topotest.py
context diff:
*** before.py
--- after.py
***************
*** 1,4 ****
! bacon
! eggs
! ham
guido
--- 1,4 ----
! python
! eggy
! hamster
guido
unified diff:
--- before.py
+++ after.py
@@ -1,4 +1,4 @@
-bacon
-eggs
-ham
+python
+eggy
+hamster
guido
Unified diff is much more common (default pretty much everywhere.)
> topotests: change from "context" to "unified" diff

- all-protocol-startup/r1/show_isis_interface_detail.ref
- all-protocol-startup/test_all_protocol_startup.py
Fix check for "show isis interface" to allow different circuit ids than 1
> all-protocol-startup/isis: Fix for PR 1176

- lib/topogen.py
- lib/topotest.py
Make the JSON failure message more straightforward by diffing the compared dictionaries and pointing out the differences.
Example output:
```
>           assert topotest.json_cmp(output, expected) is None, assertmsg
E           AssertionError: Zebra IPv4 Routing Table verification failed for router r1
E           assert json["192.168.1.0/24"] value is different (
E             --- Expected value
E             +++ Current value
E             @@ -3 +3 @@
E             -        "distance": 0, 
E             +        "distance": 90, 
E             @@ -8,0 +9 @@
E             +                "interfaceIndex": 2, 
E             @@ -20,0 +22 @@
E             +                "interfaceIndex": 2, )
E             json["192.168.3.0/24"] value is different (
E             --- Expected value
E …
```
> Improve JSON error output

- eigrp-topo1/r1/show_ip_route.json_ref
- eigrp-topo1/r2/show_ip_route.json_ref
- eigrp-topo1/r3/show_ip_route.json_ref
- Distance used to be wrong (0), new commit fixes this (90). To avoid breaking older outstanding Pull Requests, remove the distance check
> eigrp-topo1: Remove check for EIGRP distance

- ldp-topo1/r1/ip_mpls_route.ref
- ldp-topo1/r1/ip_mpls_route.ref-1
- ldp-topo1/r2/ip_mpls_route.ref
- ldp-topo1/r2/ip_mpls_route.ref-1
- ldp-topo1/r3/ip_mpls_route.ref
- ldp-topo1/r3/ip_mpls_route.ref-1
- ldp-topo1/r4/ip_mpls_route.ref
- ldp-topo1/r4/ip_mpls_route.ref-1
- ldp-topo1/test_ldp_topo1.py
PR #1213 in FRR changed the protocol of installed LSPs. To avoid breaking
older outstanding Pull Requests, remove the protocol check.
Signed-off-by: Renato Westphal <renato@opensourcerouting.org>
> ldp-topo1: Remove check for protocol in installed LSPs

- eigrp-topo1/r1/show_ip_eigrp.json
- eigrp-topo1/r2/show_ip_eigrp.json
- eigrp-topo1/r3/show_ip_eigrp.json
- eigrp-topo1/test_eigrp_topo1.py
Transform 'show ip eigrp topo' output into data structures and compare using json_cmp() to avoid expecting output order.
This is a more definite solution for the problem solution proposed here: https://github.com/FRRouting/topotests/pull/37
Since we have the output in this format now, feel free to remove fields from comparison to avoid more false-positives.
> Solve EIGRP topo output ordering problem

- lib/topogen.py
Save more information in log directory to help debugging issues later.
Extra: save the `zebra -v` output to catch misconfiguration.
> Save diagnostics to log directory

- ldp-topo1/test_ldp_topo1.py
- ospf6-topo1/test_ospf6_topo1.py
- Generic Debian only has a single space in front of “proto” in the linux shell routing outptu
> Fix output to allow it on generic Debian

- ldp-vpls-topo1/test_ldp_vpls_topo1.py
Fix an assertion on ldp test that wasn't showing useful information.
> ldp-vpls-topo1: fix a json_cmp result assert

- ldp-vpls-topo1/r1/show_ip_ospf_neighbor.ref
- ldp-vpls-topo1/r1/show_ip_ospf_neighbor.ref-old-nolist
- ldp-vpls-topo1/r2/show_ip_ospf_neighbor.ref
- ldp-vpls-topo1/r2/show_ip_ospf_neighbor.ref-old-nolist
- ldp-vpls-topo1/r3/show_ip_ospf_neighbor.ref
- ldp-vpls-topo1/r3/show_ip_ospf_neighbor.ref-old-nolist
- ldp-vpls-topo1/test_ldp_vpls_topo1.py
Adjust format to new version as introduced by FRR PR 1383
> ldp-vpls-topo1: Allow ospf neighbor json command with list (new) and dict (old)

- lib/test/test_version.py
- lib/topotest.py
It was found a regression on an edge case when the second number in the
comparison was (at least) 2 numbers longer the comparison would fail
with a wrong return value. It succeeded for some cases because the
first comparison in the exception was correct, but not the second.
> topotest: fix a regression in version_cmp

- lib/topogen.py
Use the pytest assert function to be able to report to pytest failures
that happened inside the API.
Signed-off-by: Rafael Zalamena <rzalamena@opensourcerouting.org>
> topogen: import pytest assert function

- bgp_l3vpn_to_bgp_vrf/customize.py
- bgp_l3vpn_to_bgp_vrf/scripts/adjacencies.py
- bgp_l3vpn_to_bgp_vrf/scripts/check_linux_mpls.py
- bgp_l3vpn_to_bgp_vrf/scripts/check_linux_vrf.py
- bgp_l3vpn_to_bgp_vrf/test_bgp_l3vpn_to_bgp_vrf.py
arm 7 currently skipped due to missing mpls modules, arm8 fails with 4.9 kernel.
> bgp_l3vpn_to_bgp_vrf: skip test on arm processors with kernel's older than 4.11

- ldp-vpls-topo1/r1/show_ip_ospf_neighbor.json
- ldp-vpls-topo1/r2/show_ip_ospf_neighbor.json
- ldp-vpls-topo1/r3/show_ip_ospf_neighbor.json
- ldp-vpls-topo1/test_ldp_vpls_topo1.py
Support the new OSPF JSON output format for `show ip ospf neighbor
json` introduced in FRR's PR 1723.
Signed-off-by: Rafael Zalamena <rzalamena@opensourcerouting.org>
Reference: https://github.com/FRRouting/frr/pull/1723
> ldp-vpls-topo1: support new OSPF JSON format

- bgp_vrf_netns/test_bgp_vrf_netns_topo.py
It seems vrf netns is not working on 32 bit platforms.
For that, the test should be cancelled.
Signed-off-by: Philippe Guibert <philippe.guibert@6wind.com>
> bgp_vrf_netns: do not run test on 32 bit linux machines

- bgp_vrf_netns/test_bgp_vrf_netns_topo.py
revert
https://github.com/FRRouting/topotests/pull/77
bgp_vrf_netns: do not run test on 32 bit linux machines
Signed-off-by: Philippe Guibert <philippe.guibert@6wind.com>
> bgp_vrf_netns: revert changes from topotest 77

- bgp_l3vpn_to_bgp_vrf/scripts/check_linux_mpls.py
- bgp_l3vpn_to_bgp_vrf/scripts/check_routes.py
Check CE routes from CE in another VRF attached to same PE router. Relies
on FRR bug fix to not require labeled nexthop for paths that go only
through PE router and not mpls core.
> bgp_l3vpn_to_bgp_vrf: use FRR PR #2053

- lib/topotest.py
still report cores as asserts in master (5.1)
> lib: don't report cores on exit as asserts in 5.0

- lib/topotest.py
Do not provide a staticd.conf to force staticd to read it's config
from zebra.conf
> lib: Fix staticd extension

- isis-topo1/r3/r3_route6.json
- isis-topo1/r3/zebra.conf
- isis-topo1/r4/r4_route6.json
- isis-topo1/r4/r4_topology.json
- isis-topo1/r5/r5_route6.json
- isis-topo1/r5/r5_route6_linux.json
- isis-topo1/r5/zebra.conf
The v6 isis topology didn't match the description and illustration. This adjusts the isis configurations and the expected test results so that everything is in agreement.
Signed-off-by: Mark Stapp <mjs@voltanet.io>
> isis-topo1: make isis topology match .dot file

- .gitignore
- isis-topo1/r1/r1_topology.json
- isis-topo1/r2/r2_topology.json
- isis-topo1/r3/r3_topology.json
- isis-topo1/r4/r4_topology.json
- isis-topo1/r5/r5_topology.json
- isis-topo1/test_isis_topo1.py
- lib/test/test_json.py
- lib/topogen.py
- lib/topotest.py
This PR bring some topotests improvements, like:
* Do a proper module check (helps running topotests in `docker`);
* Ignore new py.test temporary files/directories;
* Make `json_cmp` more flexible by allowing JSON data that begin with a list;
> Topotests misc improvements

- bgp-ecmp-topo1/test_bgp_ecmp_topo1.py
- bgp_vrf_netns/test_bgp_vrf_netns_topo.py
- isis-topo1/test_isis_topo1.py
- ldp-vpls-topo1/test_ldp_vpls_topo1.py
- lib/topotest.py
- ospf-topo1/test_ospf_topo1.py
Based on Lou's feedback, I'm implementing some ideias to better display test duration and reduce CI system instabilities.
First step is to improve the `run_and_expect` function, then figure out recurring paterns to create functions that can be reused.
Example of recurring patterns:
* Compare router output with file (text);
* Compare router output with file (JSON);
* Compare linux output with file (e.g. `ip route`);
Another improvements that may enter here:
* Reduce protocol timers to avoid `sleep` code;
* Start routers/hosts/exabgp concurrently instead of waiting one by one;
> topotests: test timers improvements

- ospf-topo1-vrf/test_ospf_topo1_vrf.py
- ospf-topo1/test_ospf_topo1.py
Use standardized code and fix assert messages to include errors.
Signed-off-by: Rafael Zalamena <rzalamena@opensourcerouting.org>
---
This PR is a response to this CI system run failure:
https://ci1.netdef.org/browse/FRR-FRRPULLREQ-4931/
In this PR:
https://github.com/FRRouting/frr/pull/2875
Missing messages:
**test_ospf_topo1_vrf test_ospf_kernel_route**
```
AssertionError: OSPF IPv4 route mismatch in router "r1" assert False
E   AssertionError: OSPF IPv4 route mismatch in router "r1"
assert False
```
**test_ospf_topo1_vrf test_ospf_link_down_kernel_route**
```
AssertionError: OSPF IPv4 route mismatch in router "r1" after link down assert False
E   AssertionError: OSPF IPv4 route mismatch in router "r1" after link down
assert False
```
> ospf-topo1-vrf: show errors and reduce code

- lib/topotest.py
The `strip` function is actually a method of the String object.
Signed-off-by: Rafael Zalamena <rzalamena@opensourcerouting.org>
> lib: fix `ip4_route_zebra` header removal code

- ospf6-topo1/r1/ip_6_address.ref
- ospf6-topo1/r2/ip_6_address.ref
- ospf6-topo1/r3/ip_6_address.ref
- ospf6-topo1/r4/ip_6_address.ref
- ospf6-topo1/test_ospf6_topo1.py
Topotests would fail with errors like these:
AssertionError: Linux Kernel IPv6 Routing Table verification failed for router r1:
--- actual OSPFv3 IPv6 routing table
+++ expected OSPFv3 IPv6 routing table
@@ -8,6 +8,6 @@
fc00:4:4:4::/64 via fe80::__(r3-sw5)__ dev r1-sw5 proto XXXX metric 20 pref medium
fc00:a:a:a::/64 dev r1-sw5 proto XXXX metric 256 pref medium
fc00:b:b:b::/64 via fe80::__(r3-sw5)__ dev r1-sw5 proto XXXX metric 20 pref medium
-fe80::/64 dev lo proto XXXX metric 256 pref medium
fe80::/64 dev r1-stubnet proto XXXX metric 256 pref medium
-fe80::/64 dev r1-sw5 proto XXXX metric 256 pref medium
+fe80::/64 dev r1-sw5 proto XXXX metric 256 pref medium
+unreachable fe80::/64 dev lo proto XXXX metric 256 error -101 pref medium
Resolve this by not comparing link-local routes. …
> ospf6-topo1: Don't compare link-local routes

- docker/README.md
- docker/frr-topotests.sh
Signed-off-by: Christian Franke <chris@opensourcerouting.org>
> docker: Improve README and frr-topotests usage

- docker/inner/entrypoint.sh
The default entrypoint should exit if FRR fails to compile.
> bugfix: Fail on compile error

- bgp-ecmp-topo1/test_bgp_ecmp_topo1.py
This PR fixes and improves the `bgp-ecmp-topo1` topology test. FRR's PR https://github.com/FRRouting/frr/pull/3205 is waiting on this to be able to be merged.
> bgp-ecmp-topo1: fix and improve topology test

- Dockerfile
- docker/inner/compile_frr.sh
Recent versions of FRR require libyang to build. So install it from
the FRR CI servers.
Signed-off-by: Christian Franke <chris@opensourcerouting.org>
> Dockerfile: Install libyang

- lib/topotest.py
Add a breadcrumb for people testing to hopefully allow
them to figure out what is going wrong when they
are testing different versions of FRR using
topotests and staticd is not running because
this version of staticd needs to be cleaned up
Signed-off-by: Donald Sharp <sharpd@cumulusnetworks.com>
> Add a tiny breadcrumb to hopefully help end user
